export enum routesEnum {
  users = 'users',
  roles = 'roles',
  permissions = 'permissions',
  auth = 'auth',
  goals = 'goals',
  tasks = 'tasks',
  diaries = 'diaries',
  profile = 'profile',
  statistics = 'statistics',
  login = 'login',
  logout = 'logout',
  register = 'register',
  changePassword = 'changePassword',
  forgotPassword = 'forgotPassword',
  resetPassword = 'resetPassword',
  categories = 'categories',
  habits = 'habits',
  subtasks = 'subtasks',
}
