/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/_home'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as HomeUserImport } from './routes/_home/user'
import { Route as HomeRolesImport } from './routes/_home/roles'
import { Route as HomeGoalImport } from './routes/_home/goal'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup/route'
import { Route as AuthLoginRouteImport } from './routes/_auth/login/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgotPassword/route'
import { Route as HomeUsersIndexImport } from './routes/_home/users/index'
import { Route as HomeTaskIndexImport } from './routes/_home/task/index'
import { Route as HomeRolesIndexImport } from './routes/_home/roles/index'
import { Route as HomeProfileIndexImport } from './routes/_home/profile/index'
import { Route as HomeMorningPaperIndexImport } from './routes/_home/morningPaper/index'
import { Route as HomeHabitIndexImport } from './routes/_home/habit/index'
import { Route as HomeGoalIndexImport } from './routes/_home/goal/index'
import { Route as HomeFocusIndexImport } from './routes/_home/focus/index'
import { Route as HomeDiaryIndexImport } from './routes/_home/diary/index'
import { Route as HomeCalenderIndexImport } from './routes/_home/calender/index'
import { Route as HomeAnalyticsIndexImport } from './routes/_home/analytics/index'
import { Route as HomeUsersAddImport } from './routes/_home/users/add'
import { Route as HomeRolesAddImport } from './routes/_home/roles/add'
import { Route as HomeGoalIdImport } from './routes/_home/goal/$id'
import { Route as HomeUsersEditIdImport } from './routes/_home/users/edit.$id'
import { Route as HomeUsersDeleteIdImport } from './routes/_home/users/delete.$id'
import { Route as HomeRolesEditIdImport } from './routes/_home/roles/edit.$id'
import { Route as HomeRolesDeleteIdImport } from './routes/_home/roles/delete.$id'
import { Route as HomeRolesIdPermissionsImport } from './routes/_home/roles/$id.permissions'
import { Route as HomeGoalTasksTaskIdImport } from './routes/_home/goal/tasks.$taskId'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeUserRoute = HomeUserImport.update({
  path: '/user',
  getParentRoute: () => HomeRoute,
} as any)

const HomeRolesRoute = HomeRolesImport.update({
  path: '/roles',
  getParentRoute: () => HomeRoute,
} as any)

const HomeGoalRoute = HomeGoalImport.update({
  path: '/goal',
  getParentRoute: () => HomeRoute,
} as any)

const AuthSignupRouteRoute = AuthSignupRouteImport.update({
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRouteRoute = AuthLoginRouteImport.update({
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRouteRoute = AuthForgotPasswordRouteImport.update({
  path: '/forgotPassword',
  getParentRoute: () => AuthRoute,
} as any)

const HomeUsersIndexRoute = HomeUsersIndexImport.update({
  path: '/users/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeTaskIndexRoute = HomeTaskIndexImport.update({
  path: '/task/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeRolesIndexRoute = HomeRolesIndexImport.update({
  path: '/',
  getParentRoute: () => HomeRolesRoute,
} as any)

const HomeProfileIndexRoute = HomeProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeMorningPaperIndexRoute = HomeMorningPaperIndexImport.update({
  path: '/morningPaper/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeHabitIndexRoute = HomeHabitIndexImport.update({
  path: '/habit/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeGoalIndexRoute = HomeGoalIndexImport.update({
  path: '/',
  getParentRoute: () => HomeGoalRoute,
} as any)

const HomeFocusIndexRoute = HomeFocusIndexImport.update({
  path: '/focus/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeDiaryIndexRoute = HomeDiaryIndexImport.update({
  path: '/diary/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeCalenderIndexRoute = HomeCalenderIndexImport.update({
  path: '/calender/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeAnalyticsIndexRoute = HomeAnalyticsIndexImport.update({
  path: '/analytics/',
  getParentRoute: () => HomeRoute,
} as any)

const HomeUsersAddRoute = HomeUsersAddImport.update({
  path: '/users/add',
  getParentRoute: () => HomeRoute,
} as any)

const HomeRolesAddRoute = HomeRolesAddImport.update({
  path: '/add',
  getParentRoute: () => HomeRolesRoute,
} as any)

const HomeGoalIdRoute = HomeGoalIdImport.update({
  path: '/$id',
  getParentRoute: () => HomeGoalRoute,
} as any)

const HomeUsersEditIdRoute = HomeUsersEditIdImport.update({
  path: '/users/edit/$id',
  getParentRoute: () => HomeRoute,
} as any)

const HomeUsersDeleteIdRoute = HomeUsersDeleteIdImport.update({
  path: '/users/delete/$id',
  getParentRoute: () => HomeRoute,
} as any)

const HomeRolesEditIdRoute = HomeRolesEditIdImport.update({
  path: '/edit/$id',
  getParentRoute: () => HomeRolesRoute,
} as any)

const HomeRolesDeleteIdRoute = HomeRolesDeleteIdImport.update({
  path: '/delete/$id',
  getParentRoute: () => HomeRolesRoute,
} as any)

const HomeRolesIdPermissionsRoute = HomeRolesIdPermissionsImport.update({
  path: '/$id/permissions',
  getParentRoute: () => HomeRolesRoute,
} as any)

const HomeGoalTasksTaskIdRoute = HomeGoalTasksTaskIdImport.update({
  path: '/tasks/$taskId',
  getParentRoute: () => HomeGoalRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_home': {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgotPassword': {
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthImport
    }
    '/_auth/signup': {
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthImport
    }
    '/_home/goal': {
      preLoaderRoute: typeof HomeGoalImport
      parentRoute: typeof HomeImport
    }
    '/_home/roles': {
      preLoaderRoute: typeof HomeRolesImport
      parentRoute: typeof HomeImport
    }
    '/_home/user': {
      preLoaderRoute: typeof HomeUserImport
      parentRoute: typeof HomeImport
    }
    '/_home/goal/$id': {
      preLoaderRoute: typeof HomeGoalIdImport
      parentRoute: typeof HomeGoalImport
    }
    '/_home/roles/add': {
      preLoaderRoute: typeof HomeRolesAddImport
      parentRoute: typeof HomeRolesImport
    }
    '/_home/users/add': {
      preLoaderRoute: typeof HomeUsersAddImport
      parentRoute: typeof HomeImport
    }
    '/_home/analytics/': {
      preLoaderRoute: typeof HomeAnalyticsIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/calender/': {
      preLoaderRoute: typeof HomeCalenderIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/diary/': {
      preLoaderRoute: typeof HomeDiaryIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/focus/': {
      preLoaderRoute: typeof HomeFocusIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/goal/': {
      preLoaderRoute: typeof HomeGoalIndexImport
      parentRoute: typeof HomeGoalImport
    }
    '/_home/habit/': {
      preLoaderRoute: typeof HomeHabitIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/morningPaper/': {
      preLoaderRoute: typeof HomeMorningPaperIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/profile/': {
      preLoaderRoute: typeof HomeProfileIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/roles/': {
      preLoaderRoute: typeof HomeRolesIndexImport
      parentRoute: typeof HomeRolesImport
    }
    '/_home/task/': {
      preLoaderRoute: typeof HomeTaskIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/users/': {
      preLoaderRoute: typeof HomeUsersIndexImport
      parentRoute: typeof HomeImport
    }
    '/_home/goal/tasks/$taskId': {
      preLoaderRoute: typeof HomeGoalTasksTaskIdImport
      parentRoute: typeof HomeGoalImport
    }
    '/_home/roles/$id/permissions': {
      preLoaderRoute: typeof HomeRolesIdPermissionsImport
      parentRoute: typeof HomeRolesImport
    }
    '/_home/roles/delete/$id': {
      preLoaderRoute: typeof HomeRolesDeleteIdImport
      parentRoute: typeof HomeRolesImport
    }
    '/_home/roles/edit/$id': {
      preLoaderRoute: typeof HomeRolesEditIdImport
      parentRoute: typeof HomeRolesImport
    }
    '/_home/users/delete/$id': {
      preLoaderRoute: typeof HomeUsersDeleteIdImport
      parentRoute: typeof HomeImport
    }
    '/_home/users/edit/$id': {
      preLoaderRoute: typeof HomeUsersEditIdImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute.addChildren([
    AuthForgotPasswordRouteRoute,
    AuthLoginRouteRoute,
    AuthSignupRouteRoute,
  ]),
  HomeRoute.addChildren([
    HomeGoalRoute.addChildren([
      HomeGoalIdRoute,
      HomeGoalIndexRoute,
      HomeGoalTasksTaskIdRoute,
    ]),
    HomeRolesRoute.addChildren([
      HomeRolesAddRoute,
      HomeRolesIndexRoute,
      HomeRolesIdPermissionsRoute,
      HomeRolesDeleteIdRoute,
      HomeRolesEditIdRoute,
    ]),
    HomeUserRoute,
    HomeUsersAddRoute,
    HomeAnalyticsIndexRoute,
    HomeCalenderIndexRoute,
    HomeDiaryIndexRoute,
    HomeFocusIndexRoute,
    HomeHabitIndexRoute,
    HomeMorningPaperIndexRoute,
    HomeProfileIndexRoute,
    HomeTaskIndexRoute,
    HomeUsersIndexRoute,
    HomeUsersDeleteIdRoute,
    HomeUsersEditIdRoute,
  ]),
])

/* prettier-ignore-end */
